version: '3.3'

services:
  
  strapi:
    container_name: rebook-back-prod
    image: strapi/strapi:latest
    restart: always
    env_file:
      - .env/variables-back-prod.env
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"

  react:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-front-prod
    container_name: rebook-front-prod
    restart: always
    env_file:
      - .env/variables-front-prod.env
    ports:
      - "80:80"

