version: '3.8'

services:

  strapi:
    container_name: rebook-back-dev
    image: strapi/strapi:latest
    restart: always
    env_file:
      - .env/variables-back-dev.env
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
      
  react:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-front-dev
    container_name: rebook-front-dev
    restart: always
    env_file:
      - .env/variables-front-dev.env
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

