version: '3'

services:
  rebook:
    image: ${REBOOK_IMAGE}
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    env_file:
      - deploy/env
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

volumes:
  postgres_data:
