version: '3'

services:
  rebook:
    image: ${REBOOK_IMAGE}
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    env_file:
      - deploy/env
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user_${INSTANCE_NAME}
      - POSTGRES_PASSWORD=db_password_${INSTANCE_NAME}
      - POSTGRES_DB=db_${INSTANCE_NAME}

volumes:
  postgres_data:
