name: Build docker image

on: [push]

env:
  BUILD_IMAGE_NAME: AureProd/rebook/build:${{ github.sha }}
  IMAGE_NAME: AureProd/rebook:${{ github.ref }}_latest

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of branch ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.BUILD_IMAGE_NAME }} ./api ./api/config/Dockerfile

      - name: Run Trivy all vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ env.BUILD_IMAGE_NAME }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results-all.sarif

      - name: Run Trivy unfixed vulnerability scanner 
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ env.BUILD_IMAGE_NAME }}
          exit-code: '1'
          ignore-unfixed: true
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results-unfixed.sarif

      - name: Upload Trivy scan results all to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-all.sarif'

      - name: Upload Trivy scan results unfixed to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-unfixed.sarif'
          
      - name: Push Docker image
        run: |
          docker tag ${{ env.BUILD_IMAGE_NAME }} ${{ IMAGE_NAME }}
          docker push ${{ IMAGE_NAME }}
