name: Build docker image

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of branch ${{ github.ref_name }}
        uses: actions/checkout@v4

      - name: Get docker image name
        run: echo "DOCKER_IMAGE=ghcr.io/aureprod/rebook:$(git describe --tags --match 'v[0-9]*.[0-9]*.[0-9]' --dirty --always)" >> $GITHUB_ENV

      - name: Pre-commit code check
        uses: pre-commit/action@v3.0.1

      - name: Log in to Docker registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.REBOOK_CI_PACKAGE_RW }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} --build-arg "PYTHON_VERSION=$(cat .python-version)" -f ./deploy/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}'
          ignore-unfixed: true

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}
